name: Create M33AurasModelPaths Update Pull Request

on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  modelPathsUpdate:
    if: github.repository == 'm33shoq/M33Auras'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: leafo/gh-actions-lua@v12

      - name: Update M33AurasModelPaths from wago.tools
        run: |
          cd .github/scripts/
          ./update-model-paths.sh
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: update-modelpaths
          commit-message: Update M33AurasModelPaths from wago.tools
          title: Update M33AurasModelPaths from wago.tools
          body: Update M33AurasModelPaths from wago.tools
          delete-branch: true
